version: "3"

services:
  ui:
    build: ./client
    container_name: shortly_app
    ports:
      - "8080:8080"
    depends_on:
      - api
    environment:
      - VUE_APP_TITLE=Shortly
      - VUE_APP_API_URL=http://localhost:4000/api
  api:
    build: ./server
    container_name: shortly_api
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017
  mongo:
    image: mongo
    container_name: shortly_mongo
    ports:
      - "27017:27017"
